# GLOBAL

    # fix some dragging issues with XWayland
    windowrule {
        name = xwayland-fix

        no_focus = on

        match:class = ^$
        match:title = ^$
        match:xwayland = true
        match:float = true
        match:fullscreen = false
        match:pin = false
    }

    windowrule = suppress_event maximize # ignore maximize requests from apps
    windowrule = match:title Свойства, float on

# APPLICATIONS

    windowrule {
        name = pulseaudio

        float = on
        size = 30% 50%
        move = -50% 5%

        match:title = Громкость
        match:class = org.pulseaudio.pavucontrol
    }

    windowrule {
        name = yandex-music

        fullscreen = on
        workspace = special:music

        match:class = YandexMusic
    }

    windowrule {
        name = galculator

        float = on
        center = on
        size = 365 365

        match:title = galculator
    }

    windowrule {
        name = telegram

        center = on
        workspace = name:communication

        match:class = org.telegram.desktop
    }

    windowrule {
        name = discord

        center = on
        workspace = name:communication

        match:class = discord
    }

    windowrule = match:class $browser, workspace name:web # BROWSER
