# WEB
workspace = name:web, on-created-empty:$browser
bind = SUPER, G, exec, $HYPRSCRIPTS/move_to_workspace_with_ret.sh web
bind = SUPER + SHIFT, G, movetoworkspacesilent, name:web

# CODE
workspace = name:code, on-created-empty:kitty
bind = SUPER, D, exec, $HYPRSCRIPTS/move_to_workspace_with_ret.sh code
bind = SUPER SHIFT, D, movetoworkspacesilent, name:code

# MAIN
workspace = name:main, default:true
bind = SUPER, W, exec, $HYPRSCRIPTS/move_to_workspace_with_ret.sh main
bind = SUPER SHIFT, W, movetoworkspacesilent, name:main

# COMMUNICATION
workspace = name:communication, on-created-empty:Telegram
bind = SUPER, X, exec, $HYPRSCRIPTS/move_to_workspace_with_ret.sh communication
bind = SUPER SHIFT, X, movetoworkspacesilent, name:communication

# SPECIAL:MUSIC
workspace = special:music, on-created-empty:/opt/yandex-music/yandexmusic
bind = SUPER, S, togglespecialworkspace, music
bind = , XF86Launch3, togglespecialworkspace, music
bind = SUPER SHIFT, S, movetoworkspace, special:music
